# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Blog do Gabs
tagline:             'Um rascunho de tudo o que aprendo na Agrid'
description:         ''
url:                 http://givigier.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Gabriel Givigier
  url:               http://givigier.com
  email:             gabriel@givigier.com

# Custom vars
version:             1.0.0
